version: '3.0'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - ./src/database/dumps/:/docker-entrypoint-initdb.d/